export enum HttpMessage {
  CONTINUE = 'continue',
  SWITCHING_PROTOCOLS = 'switching_protocols',
  PROCESSING = 'processing',
  EARLY_HINTS = 'early_hints',

  OK = 'ok',
  CREATED = 'created',
  ACCEPTED = 'accepted',
  NON_AUTHORITATIVE_INFORMATION = 'non_authoritative_information',
  NO_CONTENT = 'no_content',
  RESET_CONTENT = 'reset_content',
  PARTIAL_CONTENT = 'partial_content',

  AMBIGUOUS = 'multiple_choices',
  MOVED_PERMANENTLY = 'moved_permanently',
  FOUND = 'found',
  SEE_OTHER = 'see_other',
  NOT_MODIFIED = 'not_modified',
  TEMPORARY_REDIRECT = 'temporary_redirect',
  PERMANENT_REDIRECT = 'permanent_redirect',

  BAD_REQUEST = 'bad_request',
  UNAUTHORIZED = 'unauthorized',
  PAYMENT_REQUIRED = 'payment_required',
  FORBIDDEN = 'forbidden',
  NOT_FOUND = 'not_found',
  METHOD_NOT_ALLOWED = 'method_not_allowed',
  NOT_ACCEPTABLE = 'not_acceptable',
  PROXY_AUTHENTICATION_REQUIRED = 'proxy_authentication_required',
  REQUEST_TIMEOUT = 'request_timeout',
  CONFLICT = 'conflict',
  GONE = 'gone',
  LENGTH_REQUIRED = 'length_required',
  PRECONDITION_FAILED = 'precondition_failed',
  PAYLOAD_TOO_LARGE = 'payload_too_large',
  URI_TOO_LONG = 'uri_too_long',
  UNSUPPORTED_MEDIA_TYPE = 'unsupported_media_type',
  REQUESTED_RANGE_NOT_SATISFIABLE = 'requested_range_not_satisfiable',
  EXPECTATION_FAILED = 'expectation_failed',
  I_AM_A_TEAPOT = 'i_am_a_teapot',
  MISDIRECTED = 'misdirected_request',
  UNPROCESSABLE_ENTITY = 'unprocessable_entity',
  FAILED_DEPENDENCY = 'failed_dependency',
  PRECONDITION_REQUIRED = 'precondition_required',
  TOO_MANY_REQUESTS = 'too_many_requests',

  INTERNAL_SERVER_ERROR = 'internal_server_error',
  NOT_IMPLEMENTED = 'not_implemented',
  BAD_GATEWAY = 'bad_gateway',
  SERVICE_UNAVAILABLE = 'service_unavailable',
  GATEWAY_TIMEOUT = 'gateway_timeout',
  HTTP_VERSION_NOT_SUPPORTED = 'http_version_not_supported',
}
