// 🚫 Do not edit this file manually! It is automatically updated when running `pnpm feat:gen`.
import { CreateExampleService } from './create-example/create-example.service';

export { CreateExampleDto } from './create-example/create-example.dto';
export { mapCreateExampleToDto } from './create-example/create-example.mapper';

export const features = [CreateExampleService];
