// 🚫 Do not edit this file manually! It is automatically updated when running `pnpm feat:gen`.
import { Provider } from '@nestjs/common';
import { CreateExampleService } from './create-example/create-example.service';
import { GrpcServerEchoExampleService } from './grpc-server-echo-example/grpc-server-echo-example.service';
import { GrpcClientEchoExampleService } from './grpc-client-echo-example/grpc-client-echo-example.service';

export { CreateExampleDto } from './create-example/create-example.dto';
export { mapCreateExampleToDto } from './create-example/create-example.mapper';
export { GrpcServerEchoExampleDto } from './grpc-server-echo-example/grpc-server-echo-example.dto';
export { mapGrpcServerEchoExampleToDto } from './grpc-server-echo-example/grpc-server-echo-example.mapper';
export { GrpcClientEchoExampleDto } from './grpc-client-echo-example/grpc-client-echo-example.dto';
export { mapGrpcClientEchoExampleToDto } from './grpc-client-echo-example/grpc-client-echo-example.mapper';

export const features: Provider[] = [CreateExampleService, GrpcServerEchoExampleService, GrpcClientEchoExampleService];
