#!/usr/bin/env node
/* eslint-disable @typescript-eslint/no-var-requires */

const fs = require('fs');
const path = require('path');

const colors = {
  reset: '\x1b[0m',
  red: '\x1b[31m',
  green: '\x1b[32m',
};

function exitWithUsage(message) {
  if (message) console.error(`${colors.red}❌ ${message}${colors.reset}`);
  console.error(
    'Usage: node scripts/core/create-feature.js <app> <module> <feature>\n' +
      '  <feature> may be nested, e.g. "internal/get-formality" -> features/internal/get-formality/',
  );
  process.exit(1);
}

function assert(condition, message) {
  if (!condition) {
    console.error(`${colors.red}❌ ${message}${colors.reset}`);
    process.exit(1);
  }
}

function ensureDirSync(dir) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

function toPascalCase(name) {
  return name
    .replace(/[^a-zA-Z0-9]+/g, ' ')
    .split(' ')
    .filter(Boolean)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1).toLowerCase())
    .join('');
}

function toKebabCase(name) {
  return name
    .replace(/([a-z])([A-Z])/g, '$1-$2')
    .replace(/[^a-zA-Z0-9]+/g, '-')
    .replace(/-{2,}/g, '-')
    .replace(/^-|-$/g, '')
    .toLowerCase();
}

const FEATURES_INDEX_HEADER =
  '// 🚫 Do not edit this file manually! It is automatically updated when running `pnpm feat:gen`.\n';

function stripFeaturesIndexHeader(content) {
  return content
    .replace(/^\/\/ 🚫 Do not edit this file manually![^\n]*\n+/gm, '')
    .replace(/^\/\/ Không sửa tay![^\n]*\n+/gm, '')
    .replace(/^\n+/, '');
}

function prependFeaturesIndexHeader(content) {
  const body = stripFeaturesIndexHeader(content);
  if (!body) return FEATURES_INDEX_HEADER;
  return FEATURES_INDEX_HEADER + body;
}

function writeFileIfNotExists(filePath, content) {
  if (fs.existsSync(filePath)) return false;
  fs.writeFileSync(filePath, content, 'utf8');
  return true;
}

function findMatchingDelimiter(text, startIndex, openChar, closeChar) {
  let depth = 0;
  let inSingleQuote = false;
  let inDoubleQuote = false;
  let inTemplateString = false;
  let inLineComment = false;
  let inBlockComment = false;
  let escaped = false;

  for (let i = startIndex; i < text.length; i += 1) {
    const char = text[i];
    const nextChar = text[i + 1];

    if (inLineComment) {
      if (char === '\n') inLineComment = false;
      continue;
    }

    if (inBlockComment) {
      if (char === '*' && nextChar === '/') {
        inBlockComment = false;
        i += 1;
      }
      continue;
    }

    if (inSingleQuote || inDoubleQuote || inTemplateString) {
      if (escaped) {
        escaped = false;
        continue;
      }

      if (char === '\\') {
        escaped = true;
        continue;
      }

      if (inSingleQuote && char === "'") {
        inSingleQuote = false;
      } else if (inDoubleQuote && char === '"') {
        inDoubleQuote = false;
      } else if (inTemplateString && char === '`') {
        inTemplateString = false;
      }

      continue;
    }

    if (char === '/' && nextChar === '/') {
      inLineComment = true;
      i += 1;
      continue;
    }

    if (char === '/' && nextChar === '*') {
      inBlockComment = true;
      i += 1;
      continue;
    }

    if (char === "'") {
      inSingleQuote = true;
      continue;
    }

    if (char === '"') {
      inDoubleQuote = true;
      continue;
    }

    if (char === '`') {
      inTemplateString = true;
      continue;
    }

    if (char === openChar) {
      depth += 1;
      continue;
    }

    if (char === closeChar) {
      depth -= 1;
      if (depth === 0) {
        return i;
      }
    }
  }

  return -1;
}

function addImportLine(content, importLine) {
  if (content.includes(importLine)) {
    return content;
  }

  const importRegex = /(import[^;]+;\s*)+/;
  const match = content.match(importRegex);
  if (match) {
    const lastImportBlock = match[0];
    return content.replace(lastImportBlock, lastImportBlock + importLine + '\n');
  }

  return importLine + '\n' + content;
}

function getFeatureServicesFromIndex(content) {
  const start = content.indexOf('export const features');
  if (start === -1) return [];
  const arrayStart = content.indexOf('[', start);
  const arrayEnd = findMatchingDelimiter(content, arrayStart, '[', ']');
  if (arrayEnd === -1) return [];
  return parseModuleArrayItems(content.slice(arrayStart + 1, arrayEnd));
}

function formatFeaturesExport(items) {
  if (items.length <= 1) {
    return `export const features = [${items[0] ?? ''}];`;
  }
  return `export const features = [\n${items.map((item) => `  ${item},`).join('\n')}\n];`;
}

function replaceFeaturesExport(content, items) {
  const start = content.indexOf('export const features');
  const formatted = formatFeaturesExport(items);
  if (start === -1) {
    if (content.length > 0 && !content.endsWith('\n')) content += '\n';
    return `${content}\n${formatted}\n`;
  }
  const end = content.indexOf(';', start);
  const replaceEnd = end === -1 ? content.length : end + 1;
  return content.slice(0, start) + formatted + content.slice(replaceEnd);
}

function updateFeaturesIndex(filePath, opts) {
  const { serviceClassName, dtoClassName, mapperFnName, featureBase } = opts;
  let content = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf8') : '';
  content = stripFeaturesIndexHeader(content);

  const importLine = `import { ${serviceClassName} } from '${featureBase}.service';`;
  if (!content.includes(importLine)) {
    const firstExport = content.search(/^export /m);
    if (firstExport === -1) {
      content = `${importLine}\n\n${content}`;
    } else {
      content = `${content.slice(0, firstExport)}${importLine}\n${content.slice(firstExport)}`;
    }
  }

  const dtoLine = `export { ${dtoClassName} } from '${featureBase}.dto';`;
  const mapperLine = `export { ${mapperFnName} } from '${featureBase}.mapper';`;

  for (const line of [dtoLine, mapperLine]) {
    if (content.includes(line)) continue;
    const featuresConstIdx = content.indexOf('export const features');
    if (featuresConstIdx !== -1) {
      content = `${content.slice(0, featuresConstIdx)}${line}\n${content.slice(featuresConstIdx)}`;
    } else {
      if (content.length > 0 && !content.endsWith('\n')) content += '\n';
      content += `${line}\n`;
    }
  }

  const items = getFeatureServicesFromIndex(content);
  if (!items.includes(serviceClassName)) {
    items.push(serviceClassName);
    content = replaceFeaturesExport(content, items);
  } else if (items.length === 0) {
    content = replaceFeaturesExport(content, [serviceClassName]);
  }

  fs.writeFileSync(filePath, prependFeaturesIndexHeader(content), 'utf8');
  return fs.readFileSync(filePath, 'utf8');
}

function parseModuleArrayItems(arrayContent) {
  const items = [];
  let current = '';
  let depth = 0;

  for (const char of arrayContent) {
    if (char === '[') {
      depth += 1;
      continue;
    }
    if (char === ']') {
      depth -= 1;
      continue;
    }

    if (char === ',' && depth === 0) {
      const trimmed = current.trim();
      if (trimmed) items.push(trimmed);
      current = '';
      continue;
    }

    current += char;
  }

  const trimmed = current.trim();
  if (trimmed) items.push(trimmed);
  return items;
}

function ensureModuleUsesFeaturesSpread(content, featureServices) {
  content = content.replace(
    /import\s*\{[^}]+\}\s*from\s*['"]\.\/features['"]\s*;/g,
    "import { features } from './features';",
  );
  if (!content.includes("import { features } from './features'")) {
    content = addImportLine(content, "import { features } from './features';");
  }

  const decoratorStart = content.indexOf('@Module(');
  assert(decoratorStart !== -1, 'Could not find @Module decorator');
  const objectStart = content.indexOf('{', decoratorStart);
  const objectEnd = findMatchingDelimiter(content, objectStart, '{', '}');
  assert(objectEnd !== -1, 'Could not parse @Module object');

  const objectBody = content.slice(objectStart + 1, objectEnd);
  const propertyMatch = objectBody.match(/^([ \t]*)providers\s*:\s*\[/m);
  assert(propertyMatch, 'Could not find providers array in module');

  const propertyStart = objectStart + 1 + propertyMatch.index;
  const arrayStart = content.indexOf('[', propertyStart);
  const arrayEnd = findMatchingDelimiter(content, arrayStart, '[', ']');
  assert(arrayEnd !== -1, 'Could not parse providers array');

  const arrayContent = content.slice(arrayStart + 1, arrayEnd);
  let items = parseModuleArrayItems(arrayContent).filter((item) => !featureServices.includes(item));
  items = items.filter((item) => item !== '...features');
  items.push('...features');

  const propertyIndent = propertyMatch[1];
  const inlineBody = items.join(', ');
  const itemIndent = `${propertyIndent}  `;
  const multilineBody = `\n${items.map((item) => `${itemIndent}${item},`).join('\n')}\n${propertyIndent}`;
  const newArrayContent = `providers: [${inlineBody}]`.length <= 120 ? inlineBody : multilineBody;

  return content.slice(0, arrayStart + 1) + newArrayContent + content.slice(arrayEnd);
}

function main() {
  try {
    const repoRoot = path.resolve(__dirname, '../../');
    const app = process.argv[2];
    const mod = process.argv[3];
    const feature = process.argv[4];
    if (!app || !mod || !feature) {
      exitWithUsage('Missing <app>, <module>, or <feature>.');
    }

    const appName = app.trim();
    const moduleRawName = mod.trim();
    const featureRawName = feature.trim();
    const namePattern = /^[a-zA-Z0-9\-]+$/;

    assert(namePattern.test(appName), 'App must be alphanumeric or dash.');
    assert(namePattern.test(moduleRawName), 'Module must be alphanumeric or dash.');
    // <feature> may be a nested path: each "/"-separated segment is alphanumeric/dash
    // (e.g. "get-formality" or "internal/get-formality").
    const featureSegmentsRaw = featureRawName.split('/').map((s) => s.trim());
    assert(
      featureSegmentsRaw.length > 0 && featureSegmentsRaw.every((s) => namePattern.test(s)),
      'Feature must be alphanumeric/dash segments separated by "/" (e.g. "internal/get-formality").',
    );

    const appDir = path.join(repoRoot, 'apps', appName);
    const moduleDirName = toKebabCase(moduleRawName);
    // Nested-path aware: the directory mirrors the segments, while the class base prefixes EVERY
    // segment (internal/get-formality -> InternalGetFormality) so a nested feature never collides
    // with a flat one of the same leaf in features/index.ts. A single-segment feature is unchanged.
    const featureSegments = featureSegmentsRaw.map(toKebabCase);
    const featureRelDir = featureSegments.join('/');
    const leafDirName = featureSegments[featureSegments.length - 1];
    const classBaseName = toPascalCase(featureSegments.join('-'));
    const serviceClassName = `${classBaseName}Service`;
    const dtoClassName = `${classBaseName}Dto`;
    const mapperFnName = `map${classBaseName}ToDto`;

    const moduleDir = path.join(appDir, 'src', 'modules', moduleDirName);
    const moduleFilePath = path.join(moduleDir, `${moduleDirName}.module.ts`);
    const featureDir = path.join(moduleDir, 'features', ...featureSegments);

    assert(fs.existsSync(appDir), `App not found: ${appDir}`);
    assert(fs.existsSync(moduleDir), `Module not found: ${moduleDir}`);
    assert(fs.existsSync(moduleFilePath), `Missing ${moduleFilePath}. Run module:gen first.`);

    if (fs.existsSync(featureDir)) {
      console.log(
        `${colors.red}❌ Feature already exists: apps/${appName}/src/modules/${moduleDirName}/features/${featureRelDir}${colors.reset}`,
      );
      process.exit(0);
    }

    ensureDirSync(featureDir);

    const serviceTs = `import { Injectable } from '@nestjs/common';

@Injectable()
export class ${serviceClassName} {}
`;

    const dtoTs = `export class ${dtoClassName} {}
`;

    const mapperTs = `export const ${mapperFnName} = (entity: unknown) => entity;
`;

    const serviceFileName = `${leafDirName}.service.ts`;
    const dtoFileName = `${leafDirName}.dto.ts`;
    const mapperFileName = `${leafDirName}.mapper.ts`;

    const featuresDir = path.join(moduleDir, 'features');
    const featuresIndexPath = path.join(featuresDir, 'index.ts');
    const featureBase = `./${featureRelDir}/${leafDirName}`;

    writeFileIfNotExists(path.join(featureDir, serviceFileName), serviceTs);
    writeFileIfNotExists(path.join(featureDir, dtoFileName), dtoTs);
    writeFileIfNotExists(path.join(featureDir, mapperFileName), mapperTs);

    const featuresIndexContent = updateFeaturesIndex(featuresIndexPath, {
      serviceClassName,
      dtoClassName,
      mapperFnName,
      featureBase,
    });
    const featureServices = getFeatureServicesFromIndex(featuresIndexContent);

    let moduleContent = fs.readFileSync(moduleFilePath, 'utf8');
    moduleContent = ensureModuleUsesFeaturesSpread(moduleContent, featureServices);
    fs.writeFileSync(moduleFilePath, moduleContent, 'utf8');

    console.log(
      `${colors.green}✅ Created feature: apps/${appName}/src/modules/${moduleDirName}/features/${featureRelDir}${colors.reset}`,
    );
    console.log(`${colors.green}✅ Updated features/index.ts and ${moduleDirName}.module.ts${colors.reset}`);
    console.log('Next:');
    console.log(`- Implement ${serviceClassName} and wire route in ${moduleDirName}.controller.ts`);
  } catch (err) {
    console.error(`${colors.red}❌ Error: ${err.message}${colors.reset}`);
    process.exit(1);
  }
}

main();
